# Generated by Django 5.0.1 on 2024-02-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0002_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avilable',
            new_name='available',
        ),
    ]
