# Generated by Django 5.0.1 on 2024-02-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0003_rename_avilable_product_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
