# Generated by Django 5.0.1 on 2024-03-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
